# Generated by Django 5.2.5 on 2025-09-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PixelioWallApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='watermarked_image',
            field=models.ImageField(blank=True, null=True, upload_to='watermarked-images/'),
        ),
    ]
