# Generated by Django 5.2.5 on 2025-09-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PixelioWallApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
