# Generated by Django 5.2.5 on 2025-09-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PixelioWallApp', '0002_alter_image_watermarked_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original_image',
            field=models.ImageField(unique=True, upload_to='original-images/'),
        ),
    ]
