# Generated by Django 5.2.5 on 2025-09-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PixelioWallApp', '0002_image_slug_alter_image_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='watermarked_image',
            field=models.ImageField(blank=True, default='none', upload_to='watermarked-images/'),
        ),
    ]
