# Generated by Django 5.2.5 on 2025-09-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PixelioWallApp', '0003_alter_image_original_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_short_description',
            field=models.CharField(max_length=1000),
        ),
    ]
