# Generated by Django 5.2.5 on 2025-09-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PixelioWallApp', '0003_alter_image_slug_alter_image_watermarked_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
