# Generated by Django 5.2.5 on 2025-09-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PixelioWallApp', '0004_alter_image_image_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='static/images/default_male_avatar.png', upload_to='profile/'),
        ),
    ]
